spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  security:
    secret-key: "thrYez6LBnhdKQTemNxZM2M6w9NLiY"
    token-validity-in-seconds: 86400 # token dura 1 día
    token-validity-in-seconds-for-remember-me: 2592000

application:
