name: Docker Image CI

on:
  push:
    branches:
      - 'development'

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        name: Config java 17
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set RELEASE_VERSION Environment Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-amazon-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository if missing
        uses: byu-oit/github-action-create-ecr-repo-if-missing@v2
        with:
          DOCKER_REPO_NAME: ${{ vars.AWS_ECR_REPOSITORY }}

      - name: Build and push the docker image
        env:
          AWS_ECR_DOCKER_REGISTRY: ${{ steps.login-amazon-ecr.outputs.registry }}
        run: |
          ./mvnw clean package -Ppreprod -DskipTests -Dimage-version=${{ env.RELEASE_VERSION }} 
          docker push $AWS_ECR_DOCKER_REGISTRY/${{ vars.AWS_ECR_REPOSITORY }}:${{ env.RELEASE_VERSION }}
